### ISSUE TITLE
Expand protected bundle identifier from iphone?

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/Airtest#391]
Can i know how to check iphone installed app bundle identifier?

Added star_app (bundle identifier).

**Comment by SUDARSHANCHAUDHARI** [comment]
for me, I tried the same syntax,
but then I lost the connection between WebDriver and Iproxy
connection disabled and can't connect to the device. (I doubt it is optimized and working for iOS?)

have to restart web drive Xcode project and proxy URL.

I think we cant launch the app directly because in background WebdriveAgent application is running and if we launch any app from 'start_app' command then WebdriveAgent stops working.

It is my thinking and can anybody provide the exact cause and solution for this problem

Note: for android, start_app is working as intended and without any issue

**Comment by EraChen233** [comment]
> Can i know how to check iphone installed app bundle identifier?
> 
> Added star_app (bundle identifier).

@JJunM 
For Android phones,  you can get installed app list by [list_app](https://airtest.readthedocs.io/zh_CN/latest/_modules/airtest/core/android/android.html#Android.list_app). But this interface is not implemented in iOS.
